name: drift_sqlite_async

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  drift: ^2.15.0
  sqlite_async: ^0.6.0
dev_dependencies:
  build_runner: ^2.4.8
  drift_dev: ^2.15.0
  glob: ^2.1.2
  test: ^1.25.2
